# -*- coding: utf-8 -*-
"""taller_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Shg3bQ-Xst_y-p_hU7lADPQwwNOj6aMN
"""

def functunion():
    res1 = A.union(B)
    print(res1, len(res1))


def funcinter():
  res2 = A.intersection(B)
  print(res2, len(res2))

def funcdiffer():
  res3 = A.difference(B)
  print(res3, len(res3))


def funcsymdiff():
  res4 = A.symmetric_difference(B)
  print(res4, len(res4))


A =set()
B = set()
conja = int(input("¿Cuántos elementos ingreserá para el conjunto A?"))

for i in range(1,conja+1):
  conjuntoA = int(input("Ingrese cada uno de los números"))
  A.add(conjuntoA)

print(A)

conjb = int(input("¿Cuántos elementos ingreserá para el conjunto B?"))
for j in range(1,conjb+1):
  conjuntoB = int(input("Ingrese cada uno de los números"))
  B.add(conjuntoB)

print(B)


print("SELECCIONE UNA OPERACIÓN")
print("1. Union")
print("2. Interseccion")
print("3. Diferencia")
print("4. Diferencia Simétrica")

option = int(input("¿Qué operación seleccionará?"))


if option == 1:
  functunion()

elif option == 2:
  funcinter()

elif option == 3:
  funcdiffer()

elif option == 4:
  funcsymdiff()