# -*- coding: utf-8 -*-
"""taller6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IJ3CLX_lvXzQ1-WO_YK_43LHe7civ8Ym
"""

import math

def calcos(x, es):
    termino_actual = 1.0
    result = termino_actual
    iteraciones = 0

    while True:
        iteraciones += 1
        termino_actual *= -x * x / ((2 * iteraciones) * (2 * iteraciones - 1))
        result += termino_actual

        ea = abs((result - math.cos(x)) / result) * 100

        if ea < es:
            break

    return result, ea, iteraciones

def main():
    x = float(input("Ingrese el valor en radianes: "))
    es = float(input("Ingrese el criterio de error esperado (εs): "))

    valor_estimado, error_aproximado, niteraciones = calcos(x, es)

    print(f"Valor estimado de cos({x}): {valor_estimado}")
    print(f"Error aproximado relativo porcentual: {error_aproximado:.8f}%")
    print(f"Número de iteraciones realizadas: {niteraciones}")

if __name__ == "__main__":
    main()